/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Merge a single operation into state.
 * Returns a Buffer containing the serialized MergeResult (new state + delta).
 */
export declare function mergeOperation(state: Buffer, operation: Buffer): Buffer
/**
 * Merge a batch of operations sequentially into state.
 * Returns a Buffer containing the serialized BatchMergeResult.
 */
export declare function mergeBatch(state: Buffer, operations: Array<Buffer>): Buffer
/**
 * Compare two HLC timestamps.
 * Returns -1 if a < b, 0 if a == b, 1 if a > b.
 */
export declare function compareHlc(a: Buffer, b: Buffer): number
/**
 * Compute a state snapshot: consolidate state and remove tombstones.
 * Returns a Buffer containing the cleaned-up state.
 */
export declare function computeSnapshot(state: Buffer): Buffer
/**
 * Optimized benchmark merge: processes all operations in one Rust call.
 * No intermediate serialization, no state cloning per operation.
 * Returns a lightweight BenchmarkMergeResult with just the metrics + final state.
 *
 * This is O(n) per operation (HashMap lookup + insert) instead of O(n²)
 * from the clone-per-op approach in the standard merge_batch.
 */
export declare function mergeBatchBenchmark(state: Buffer, operations: Array<Buffer>): Buffer
