/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Create a room in the state store. Idempotent — no-op if room already exists. */
export declare function createRoom(roomId: string): void
/** Drop a room from the state store. Idempotent — no error if room doesn't exist. */
export declare function dropRoom(roomId: string): void
/** Get the full serialized state for a room. Errors if room not found. */
export declare function getState(roomId: string): Buffer
/**
 * Merge operations into a room's state in-place. Returns a delta Buffer.
 * Errors if room not found.
 */
export declare function mergeOps(roomId: string, operations: Array<Buffer>): Buffer
/**
 * Merge a single operation into state.
 * Returns a Buffer containing the serialized MergeResult (new state + delta).
 */
export declare function mergeOperation(state: Buffer, operation: Buffer): Buffer
/**
 * Merge a batch of operations sequentially into state.
 * Returns a Buffer containing the serialized BatchMergeResult.
 */
export declare function mergeBatch(state: Buffer, operations: Array<Buffer>): Buffer
/**
 * Compare two HLC timestamps.
 * Returns -1 if a < b, 0 if a == b, 1 if a > b.
 */
export declare function compareHlc(a: Buffer, b: Buffer): number
/**
 * Compute a state snapshot: consolidate state and remove tombstones.
 * Returns a Buffer containing the cleaned-up state.
 */
export declare function computeSnapshot(state: Buffer): Buffer
/**
 * Optimized benchmark merge: processes all operations in one Rust call.
 * No intermediate serialization, no state cloning per operation.
 * Returns a lightweight BenchmarkMergeResult with just the metrics + final state.
 *
 * This is O(n) per operation (HashMap lookup + insert) instead of O(n²)
 * from the clone-per-op approach in the standard merge_batch.
 */
export declare function mergeBatchBenchmark(state: Buffer, operations: Array<Buffer>): Buffer
